image: starefossen/ruby-node:latest


variables:
  PORT: 3000
  APP_TITLE: "topcoder x app"
  NODE_ENV: development

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

building:
  script:
    - echo "Building the app"
    - npm i
  stage: build

testing:
  script:
    - echo "Running tests"
    - npm i
    - npm test
  stage: test

deploy_dev:
  stage: deploy
  script:
    - echo "Deploying the app"
    - apt-get update -qy
    - apt-get install -y rubygems ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_DEV_APP --api-key=$HEROKU_DEV_API_KEY
  only:
  - develop
  environment:
    name: dev
    url: $HEROKU_DEV_URL

deploy_stage:
  stage: deploy
  script:
  - echo "Deploying the app"
  - apt-get update -qy
  - apt-get install -y rubygems ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
  environment:
    name: stage
    url: $HEROKU_STAGING_URL
variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive